repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
      - id: cargo-check

  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
        args: ["--verbose", "--edition", "2018", "--"]
